version: '3.8'

services:
  backend:
    image: meanto/random-joke:latest
    build: .
    ports:
      - "8888:8888"
    restart: always
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "80"
      - "--domain=welcome-cattle-regular.ngrok-free.app"
    environment:
      - NGROK_AUTHTOKEN=2vrV06cIJiiS66f8VGJaMLFfFew_7tuGr59u8UV285KGUPHGo
    ports:
      - "4040:4040"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge